# Generated by Django 3.2.5 on 2021-07-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='medium_link',
            field=models.CharField(max_length=400),
        ),
    ]
