# Generated by Django 3.2.5 on 2021-07-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/articles/article_images/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
