# Generated by Django 3.2.5 on 2021-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210720_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.CharField(default='No Tag', max_length=255),
        ),
    ]
