# Generated by Django 3.2.5 on 2021-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210720_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.CharField(default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='courses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
