# Generated by Django 3.2.5 on 2021-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.TextField()),
                ('learning', models.TextField()),
                ('get_in_touch', models.TextField()),
            ],
        ),
    ]
