# Generated by Django 3.2.5 on 2021-07-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.TextField(default='As of 2021'),
            preserve_default=False,
        ),
    ]
